// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	Password  []byte             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
