// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserInvitation = `-- name: CreateUserInvitation :exec
INSERT INTO user_invitations (token, user_id, expiry) VALUES ($1, $2, $3)
`

type CreateUserInvitationParams struct {
	Token  []byte             `json:"token"`
	UserID int64              `json:"user_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) error {
	_, err := q.db.Exec(ctx, createUserInvitation, arg.Token, arg.UserID, arg.Expiry)
	return err
}

const deleteUserInvitationByUserId = `-- name: DeleteUserInvitationByUserId :exec
DELETE FROM user_invitations WHERE user_id = $1
`

func (q *Queries) DeleteUserInvitationByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserInvitationByUserId, userID)
	return err
}
